### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by kalib** [codebrane/octohug#8]
Not sure what happened here when trying to run the migration. It seemed to start the migrations correctly but failed eventually:

...
...
...
source/_posts/2009-04-03-ii-mangue-beat.markdown
content/post/ii-mangue-beat.md
source/_posts/2009-04-08-primeiro-encontro-cearaonrailse2809909.markdown
content/post/primeiro-encontro-cearaonrailse2809909.md
source/_posts/2009-04-13-mudanca-em-meu-notebook-e-nao-vou-twittar.markdown
content/post/mudanca-em-meu-notebook-e-nao-vou-twittar.md
source/_posts/2009-04-17-convite-ao-dia-livre.markdown
content/post/convite-ao-dia-livre.md
source/_posts/2009-04-23-flisol-fortaleza-tux-ce-dara-3-livros.markdown
content/post/flisol-fortaleza-tux-ce-dara-3-livros.md
source/_posts/2009-04-29-flisol-2009-fortaleza-obrigado-tux-ce.markdown
content/post/flisol-2009-fortaleza-obrigado-tux-ce.md
source/_posts/2009-05-11-que-tal-um-pequeno-filme-para-descontrair.markdown
content/post/que-tal-um-pequeno-filme-para-descontrair.md
source/_posts/2009-05-12-so-faltava-essa-microsoft-agora-tenta-fragmentar-o-odf.markdown
content/post/so-faltava-essa-microsoft-agora-tenta-fragmentar-o-odf.md
panic: runtime error: index out of range

goroutine 1 [running]:
main.visit(0xc000152360, 0x58, 0x1115080, 0xc000079d40, 0x0, 0x0, 0x0, 0x0)
	/Users/marcelo.rocha/repos/octohug/octohug.go:157 +0x1939
path/filepath.walk(0xc000152360, 0x58, 0x1115080, 0xc000079d40, 0x11027f8, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/path/filepath/path.go:358 +0x41c
path/filepath.walk(0x10fc487, 0xd, 0x1115080, 0xc000078820, 0x11027f8, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/path/filepath/path.go:382 +0x2fe
path/filepath.Walk(0x10fc487, 0xd, 0x11027f8, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/path/filepath/path.go:404 +0x105
main.main()
	/Users/marcelo.rocha/repos/octohug/octohug.go:229 +0x10f

**Comment by kalib** [comment]
My bad, it was a broken post. Found the broken chars on it. After fixing the post, the migration worked fine.
